// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devs.sql

package devs

import (
	"context"
	"time"

	"github.com/lib/pq"
)

const createDev = `-- name: CreateDev :one
INSERT INTO devs (name, email, password, skills, bio, availability, socials) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING name, email, skills, bio, availability, socials, created_at
`

type CreateDevParams struct {
	Name         string   `json:"name"`
	Email        string   `json:"email"`
	Password     string   `json:"password"`
	Skills       []string `json:"skills"`
	Bio          string   `json:"bio"`
	Availability bool     `json:"availability"`
	Socials      []string `json:"socials"`
}

type CreateDevRow struct {
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	Skills       []string  `json:"skills"`
	Bio          string    `json:"bio"`
	Availability bool      `json:"availability"`
	Socials      []string  `json:"socials"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) CreateDev(ctx context.Context, arg CreateDevParams) (CreateDevRow, error) {
	row := q.db.QueryRowContext(ctx, createDev,
		arg.Name,
		arg.Email,
		arg.Password,
		pq.Array(arg.Skills),
		arg.Bio,
		arg.Availability,
		pq.Array(arg.Socials),
	)
	var i CreateDevRow
	err := row.Scan(
		&i.Name,
		&i.Email,
		pq.Array(&i.Skills),
		&i.Bio,
		&i.Availability,
		pq.Array(&i.Socials),
		&i.CreatedAt,
	)
	return i, err
}

const findDevByEmail = `-- name: FindDevByEmail :one
SELECT id, name, email, password FROM devs WHERE email = $1
`

type FindDevByEmailRow struct {
	ID       int32  `json:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) FindDevByEmail(ctx context.Context, email string) (FindDevByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, findDevByEmail, email)
	var i FindDevByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
	)
	return i, err
}

const findDevByID = `-- name: FindDevByID :one
SELECT name, email, skills, bio, availability, socials FROM devs WHERE id = $1
`

type FindDevByIDRow struct {
	Name         string   `json:"name"`
	Email        string   `json:"email"`
	Skills       []string `json:"skills"`
	Bio          string   `json:"bio"`
	Availability bool     `json:"availability"`
	Socials      []string `json:"socials"`
}

func (q *Queries) FindDevByID(ctx context.Context, id int32) (FindDevByIDRow, error) {
	row := q.db.QueryRowContext(ctx, findDevByID, id)
	var i FindDevByIDRow
	err := row.Scan(
		&i.Name,
		&i.Email,
		pq.Array(&i.Skills),
		&i.Bio,
		&i.Availability,
		pq.Array(&i.Socials),
	)
	return i, err
}
